# fly.toml app configuration file generated for colorfill on 2023-10-08T12:30:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "colorfill"
primary_region = "iad"

[build]

[[mounts]]
  source = "colorfill_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
